name: Content Pipeline

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      skip_fetch:
        description: 'Skip fetch step'
        required: false
        default: false
        type: boolean

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env.local
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.local
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env.local

      - name: Run Feed Fetcher
        if: ${{ !inputs.skip_fetch }}
        run: npm run pipeline:fetch
        continue-on-error: true

      - name: Run Normalizer
        run: npm run pipeline:normalize
        continue-on-error: true

      - name: Run Curator
        run: npm run pipeline:curate
        continue-on-error: true

      - name: Run Guide Formatter
        run: npm run pipeline:format-guides
        continue-on-error: true

      - name: Send notification on failure
        if: failure()
        run: |
          echo "Pipeline failed at $(date)" >> pipeline-errors.log
          # Could add Slack/Discord notification here

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: |
            pipeline-errors.log
            *.log
          retention-days: 7