name: Validate and Import Tricks

on:
  pull_request:
    paths:
      - 'data/*.json'
  push:
    branches:
      - main
    paths:
      - 'data/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Validate tricks JSON
        run: |
          FILE=$(git diff --name-only HEAD^ HEAD | grep '^data/.*\.json$' | head -n1 || true)
          if [ -z "$FILE" ]; then
            echo "No data/*.json changes detected. Skipping."; exit 0; fi
          npm run -s import-tricks:validate-file -- "$FILE"

  import:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: validate
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Determine changed file
        id: files
        run: |
          FILE=$(git diff --name-only HEAD^ HEAD | grep '^data/.*\.json$' | head -n1 || true)
          echo "file=$FILE" >> $GITHUB_OUTPUT
      - name: Import to Supabase
        if: steps.files.outputs.file
        run: npm run -s import-tricks:file -- "${{ steps.files.outputs.file }}"
